name: daily_ui
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: any
  image: ^3.0.2
  vector_math: ^2.1.0

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.0
  font_awesome_flutter: ^9.2.0
  extended_masked_text: ^2.3.1
  provider: ^6.0.2
  english_words: ^4.0.0
  transparent_image: ^2.0.0
  faker: ^2.0.0
  funvas: ^0.1.6+6
  google_fonts: ^2.3.2
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: 
  flutter_gen_runner: 

flutter_gen:
  output: lib/gen/
  line_length: 80

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/fonts/
    - assets/images/people/

  fonts:
    - family: Silkscreen
      fonts:
        - asset: assets/fonts/slkscr.ttf
        - asset: assets/fonts/slkscrb.ttf
        - asset: assets/fonts/slkscre.ttf
        - asset: assets/fonts/slkscreb.ttf
